- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Abonneer op de RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Abonneer op de Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap voor Google Webmaster Tools"
